/* symalg.c - BRISK 4.41: structure shared by all data matrices of a block (a group of any kind
 * that fixes every constraint matrix, commuting data, hidden direct sums) by the numerical block
 * diagonalisation of the matrix *-algebra the data generate (Murota, Kanno, Kojima and Kojima,
 * Japan J. Indust. Appl. Math. 27 (2010); Maehara and Murota, ibid. 27 (2010)).
 *
 * Per SDP block, the unital *-algebra A generated by C and the A_p of the block is, in a
 * suitable orthogonal basis Q, a direct sum of simple components I_{m_c} (x) M_{d_c}: Q' A_p Q
 * = diag_c (I_{m_c} (x) B_{c,p}). Restricting X to A (the trace-preserving conditional
 * expectation onto A maps PSD to PSD and keeps every <A_p, X> and <C, X>) leaves the optimal
 * value unchanged, so the block is replaced by blocks X_c of size d_c, with data m_c B_{c,p}:
 *
 *     <A_p, X> = sum_c m_c <B_{c,p}, X_c>,        X = Q diag_c (I_{m_c} (x) X_c) Q'.
 *
 * This covers the groups the exact search (symred.c) cannot see: symmetries that are not
 * signed permutations (orthogonal, continuous, hidden by a change of basis), and a structure of
 * the data that comes from no group at all. Its cost is about four n x n eigen/GEMM passes per
 * block, so it runs (-symalg -1, the default) after the exact reductions on blocks of
 * moderate size, and a cheap test first proves most blocks irreducible in O(nnz):
 *
 *   fast test: when the diagonal data matrices of the block separate every index (a random
 *   combination of them has distinct entries), A contains every diagonal matrix unit E_ii; then
 *   E_ii A_p E_jj = a_ij E_ij gives every E_ij along the edges of the sparsity graph, and a
 *   connected graph gives A = M_n: no structure. (Max-cut, theta, most relaxations.)
 *
 * The decomposition: S1, S2, S3 random combinations of the (normalised) data. The eigenspaces
 * of S1 (clusters of equal eigenvalues) lie within the components; S2 and S3 in the
 * eigenbasis join the clusters into components (any coupling above 1e-10 joins: an error only
 * merges, which is still exact). In a component whose clusters all have dimension m >= 2 the
 * couplings are scalar multiples of orthogonal m x m matrices (real type); the cluster bases
 * are aligned along a maximal spanning tree, and the result is verified on S2 and S3 in full:
 * then the component is I_m (x) M_d. A component that fails (complex or quaternion type, or an
 * accidental near-degeneracy of S1) keeps multiplicity 1, which is still exact. A component
 * whose data all vanish (a common kernel) is dropped: X = 0 there. */
#include "brisk.h"
#include <math.h>
#include <string.h>
#include <stdint.h>
double wtime(void);

static void *ax(size_t n) { void *p = malloc(n ? n : 1); if (!p) { fprintf(stderr, "brisk: out of memory (algebra symmetry)\n"); exit(1); } return p; }
static uint64_t al_rng = 0x2545f4914f6cdd1dull;
static double al_rand(void) { al_rng ^= al_rng << 13; al_rng ^= al_rng >> 7; al_rng ^= al_rng << 17; return (double)(al_rng >> 11) * (2.0 / 9007199254740992.0) - 1.0; }
static double al_weight(void) { const double r = al_rand(); return (r < 0 ? -1.0 : 1.0) * (0.5 + 0.5 * fabs(r)); }   /* |w| in [0.5, 1]: no datum is hidden by a tiny weight */
static int al_find(int *p, int x) { while (p[x] != x) { p[x] = p[p[x]]; x = p[x]; } return x; }
static int cmp_dbl(const void *a, const void *b) { const double x = *(const double *)a, y = *(const double *)b; return x < y ? -1 : x > y; }

static double sp_fro(const SpSym *A) { double s = 0; for (int q = 0; q < A->nnz; q++) s += (A->row[q] == A->col[q] ? 1.0 : 2.0) * A->val[q] * A->val[q]; return sqrt(s); }

/* S = sum_t w_t A_t / |A_t| over C (t = -1) and the constraints of the block, dense n x n */
static void al_combo(const Block *B, const double *nrm, double *S) {
    const int n = B->n;
    memset(S, 0, sizeof(double) * (size_t)n * n);
    for (int t = -1; t < B->ncon; t++) {
        const SpSym *A = t < 0 ? &B->C : &B->A[t];
        const double w = al_weight();
        if (nrm[t + 1] <= 0) continue;
        const double f = w / nrm[t + 1];
        for (int q = 0; q < A->nnz; q++) {
            const int i = A->row[q], j = A->col[q];
            S[i + (size_t)j * n] += f * A->val[q];
            if (i != j) S[j + (size_t)i * n] += f * A->val[q];
        }
    }
}

/* the fast test: when the diagonal data separate the indices, A contains every E_ii and A is
 * the direct sum of M_s over the connected components of the sparsity graph. Returns 1 when
 * that graph is connected (A = M_n), 2 when it is not (lab[i]: component of index i, *ncomp
 * components), 0 when the diagonal data do not separate the indices (no conclusion). */
static int al_fast(const Block *B, const double *nrm, int *lab, int *ncomp) {
    const int n = B->n;
    double *dg = calloc(n, sizeof(double));
    int *uf = ax(sizeof(int) * n); for (int i = 0; i < n; i++) uf[i] = i;
    int ndiag = 0;
    for (int t = -1; t < B->ncon; t++) {
        const SpSym *A = t < 0 ? &B->C : &B->A[t];
        const double w = al_weight();
        if (nrm[t + 1] <= 0) continue;
        int diag = 1;
        for (int q = 0; q < A->nnz; q++) if (A->row[q] != A->col[q]) { diag = 0; const int a = al_find(uf, A->row[q]), b = al_find(uf, A->col[q]); if (a != b) uf[a] = b; }
        if (diag) { ndiag++; for (int q = 0; q < A->nnz; q++) dg[A->row[q]] += w / nrm[t + 1] * A->val[q]; }
    }
    int ok = ndiag > 0;
    if (ok) {
        qsort(dg, n, sizeof(double), cmp_dbl);
        const double sc = fmax(fabs(dg[0]), fabs(dg[n - 1]));
        for (int i = 1; ok && i < n; i++) if (dg[i] - dg[i - 1] <= 1e-9 * sc) ok = 0;
    }
    int res = 0;
    if (ok) {
        int K = 0; for (int i = 0; i < n; i++) lab[i] = -1;
        int *rl = ax(sizeof(int) * n); for (int i = 0; i < n; i++) rl[i] = -1;
        for (int i = 0; i < n; i++) { const int r = al_find(uf, i); if (rl[r] < 0) rl[r] = K++; lab[i] = rl[r]; }
        free(rl);
        *ncomp = K; res = K == 1 ? 1 : 2;
    }
    free(dg); free(uf);
    return res;
}

#define AL_K 6
typedef struct { int d, mult, rep; double *Q; } ACmp;   /* a component: Q n x (d mult), column r d + i: copy r, index i; rep: multiplicity
                                                          * folded into Q (the irreducible path: one copy sqrt(rep) U, mult 1) */

/* T = V' S V (S overwritten by T; W scratch n x n) */
static void al_rotate(int n, const double *V, double *S, double *W) {
    const double one = 1.0, zero = 0.0;
    size_t nzc = 0; const size_t nn = (size_t)n * n;
    for (size_t q = 0; q < nn; q++) nzc += S[q] != 0.0;
    if (nzc < nn / 8) {
        /* sparse S: W = S V column by column of V, S by columns (CSC) */
        int *cp = ax(sizeof(int) * (n + 1)), *ri = ax(sizeof(int) * (nzc + 1)); double *rv = ax(sizeof(double) * (nzc + 1));
        size_t t = 0; cp[0] = 0;
        for (int j = 0; j < n; j++) { for (int i = 0; i < n; i++) { const double v = S[i + (size_t)j * n]; if (v != 0.0) { ri[t] = i; rv[t] = v; t++; } } cp[j + 1] = (int)t; }
        memset(W, 0, sizeof(double) * nn);
        for (int c = 0; c < n; c++) { double *w = W + (size_t)c * n; const double *v = V + (size_t)c * n;
            for (int j = 0; j < n; j++) { const double vj = v[j]; if (vj == 0.0) continue; for (int q = cp[j]; q < cp[j + 1]; q++) w[ri[q]] += rv[q] * vj; } }
        free(cp); free(ri); free(rv);
    } else
    BL(dgemm_)("N", "N", &n, &n, &n, &one, S, &n, V, &n, &zero, W, &n);
    BL(dgemm_)("T", "N", &n, &n, &n, &one, V, &n, W, &n, &zero, S, &n);
}

static double al_blkfro(int n, const double *T, int i0, int i1, int j0, int j1) {
    double s = 0;
    for (int j = j0; j < j1; j++) for (int i = i0; i < i1; i++) s += T[i + (size_t)j * n] * T[i + (size_t)j * n];
    return sqrt(s);
}

/* G = Oi' T[Ii, Ij] Oj (m x m); Oi, Oj m x m (NULL: identity) */
static void al_cpl(int n, int m, const double *T, int i0, int j0, const double *Oi, const double *Oj, double *G, double *w) {
    for (int b = 0; b < m; b++) for (int a = 0; a < m; a++) w[a + b * m] = T[(i0 + a) + (size_t)(j0 + b) * n];
    const double one = 1.0, zero = 0.0;
    if (Oj) { BL(dgemm_)("N", "N", &m, &m, &m, &one, w, &m, Oj, &m, &zero, G, &m); memcpy(w, G, sizeof(double) * m * m); }
    if (Oi) BL(dgemm_)("T", "N", &m, &m, &m, &one, Oi, &m, w, &m, &zero, G, &m); else memcpy(G, w, sizeof(double) * m * m);
}

/* is G = b I (relative to sc)? */
static int al_scalar(int m, const double *G, double sc, double tol) {
    for (int b = 0; b < m; b++) for (int a = 0; a < m; a++) {
        const double v = G[a + b * m];
        if (a != b ? fabs(v) > tol * sc : fabs(v - G[0]) > tol * sc) return 0;
    }
    return 1;
}

/* 4.41: an irreducible invariant subspace of a component of any type (real, complex,
 * quaternion): the cyclic closure of one vector of the first cluster under K = 6 further
 * random combinations GK of the data (two would not do: two quaternion-Hermitian 2 x 2
 * matrices generate only a Clifford subalgebra), in eigen-coordinates. The checks use S2 and
 * S3, which the closure did not see, so they hold for all the data with probability 1. On success U (per cluster a s_j x r_j block,
 * columns orthonormal, offsets uo) spans a copy, and every cluster has s_j = M r_j for one
 * M >= 2. Checked: the copy is invariant under S2 and S3 to 1e-9, and the characters agree,
 * tr(T|comp) = M tr(U'TU) and |T|comp|_F^2 = M |U'TU|_F^2 for T = S2, S3, and <S2, S3> likewise.
 * Returns r = sum r_j, or 0. */
static int al_irred(int n, const double *V, double *const *GK, int K, const double *T2, const double *T3, double sc2, double sc3,
                    const int *cs, const int *mem, int nm, double **Uout, int *uo, int *rj, int *Mout) {
    int D = 0; for (int a = 0; a < nm; a++) D += cs[mem[a] + 1] - cs[mem[a]];
    double *U = calloc((size_t)D * D + 1, sizeof(double));   /* per cluster a: s_a x (up to s_a) at offset uo[a] */
    { int o = 0; for (int a = 0; a < nm; a++) { const int sa = cs[mem[a] + 1] - cs[mem[a]]; uo[a] = o; o += sa * sa; rj[a] = 0; } }
    int *qa = ax(sizeof(int) * (D + 1)), *qc = ax(sizeof(int) * (D + 1)), qh = 0, qt = 0, r = 0, ok = 1;
    double *y = ax(sizeof(double) * (n + D + 1));
    U[uo[0]] = 1.0; rj[0] = 1; r = 1; qa[qt] = 0; qc[qt] = 0; qt++;
    const double *TT[2] = { T2, T3 }; const double sct[2] = { sc2, sc3 };
    double *z = ax(sizeof(double) * n), *wv = ax(sizeof(double) * n);
    while (qh < qt && ok) {
        const int a = qa[qh], col = qc[qh]; qh++;
        const int sa = cs[mem[a] + 1] - cs[mem[a]];
        const double *x = U + uo[a] + (size_t)col * sa;
        { const double one = 1.0, zero = 0.0; const int inc = 1;
          BL(dgemv_)("N", &n, &sa, &one, V + (size_t)cs[mem[a]] * n, &n, x, &inc, &zero, z, &inc); }
        for (int k = 0; k < K && ok; k++) {
            { const double one = 1.0, zero = 0.0; const int inc = 1;
              BL(dgemv_)("N", &n, &n, &one, GK[k], &n, z, &inc, &zero, wv, &inc); }
            double nw = 0; for (int i = 0; i < n; i++) nw += wv[i] * wv[i]; nw = sqrt(nw);
            if (nw <= 0) continue;
            for (int b = 0; b < nm && ok; b++) {
                const int sb = cs[mem[b] + 1] - cs[mem[b]];
                { const double one = 1.0, zero = 0.0; const int inc = 1;
                  BL(dgemv_)("T", &n, &sb, &one, V + (size_t)cs[mem[b]] * n, &n, wv, &inc, &zero, y, &inc); }
                double n0 = 0; for (int i = 0; i < sb; i++) n0 += y[i] * y[i]; n0 = sqrt(n0);
                if (n0 <= 1e-9 * nw) continue;
                for (int pass = 0; pass < 2; pass++) for (int q = 0; q < rj[b]; q++) {
                    const double *u = U + uo[b] + (size_t)q * sb; double d = 0;
                    for (int i = 0; i < sb; i++) d += u[i] * y[i];
                    for (int i = 0; i < sb; i++) y[i] -= d * u[i];
                }
                double n1 = 0; for (int i = 0; i < sb; i++) n1 += y[i] * y[i]; n1 = sqrt(n1);
                if (n1 <= 1e-6 * n0) continue;
                if (rj[b] >= sb || 2 * (r + 1) > D) { ok = 0; break; }   /* no multiplicity >= 2 */
                double *u = U + uo[b] + (size_t)rj[b] * sb;
                for (int i = 0; i < sb; i++) u[i] = y[i] / n1;
                qa[qt] = b; qc[qt] = rj[b]; qt++; rj[b]++; r++;
            }
        }
    }
    free(z); free(wv);
    int M = 0;
    for (int a = 0; a < nm && ok; a++) {
        const int sa = cs[mem[a] + 1] - cs[mem[a]];
        if (rj[a] == 0 || sa % rj[a]) { ok = 0; break; }
        if (!M) M = sa / rj[a]; else if (sa / rj[a] != M) ok = 0;
    }
    if (ok && M < 2) ok = 0;
    /* invariance and characters */
    for (int k = 0; k < 2 && ok; k++) {
        const double *T = TT[k];
        double trc = 0, trU = 0, frc = 0, frU = 0;
        for (int a = 0; a < nm; a++) for (int i = cs[mem[a]]; i < cs[mem[a] + 1]; i++) {
            trc += T[i + (size_t)i * n];
            for (int b = 0; b < nm; b++) for (int j = cs[mem[b]]; j < cs[mem[b] + 1]; j++) frc += T[i + (size_t)j * n] * T[i + (size_t)j * n];
        }
        for (int a = 0; a < nm && ok; a++) {
            const int sa = cs[mem[a] + 1] - cs[mem[a]];
            for (int b = 0; b < nm && ok; b++) {
                const int sb = cs[mem[b] + 1] - cs[mem[b]];
                for (int p = 0; p < rj[a]; p++) {
                    const double *u = U + uo[a] + (size_t)p * sa;
                    for (int i = 0; i < sb; i++) { double v = 0; for (int j = 0; j < sa; j++) v += T[(cs[mem[b]] + i) + (size_t)(cs[mem[a]] + j) * n] * u[j]; y[i] = v; }
                    /* coefficients on the copy's basis of cluster b, and the residual */
                    double res = 0;
                    for (int q = 0; q < rj[b]; q++) { const double *w = U + uo[b] + (size_t)q * sb; double d = 0; for (int i = 0; i < sb; i++) d += w[i] * y[i];
                        frU += d * d; if (a == b && p == q) trU += d; for (int i = 0; i < sb; i++) y[i] -= d * w[i]; }
                    for (int i = 0; i < sb; i++) res = fmax(res, fabs(y[i]));
                    if (res > 1e-9 * sct[k]) ok = 0;
                }
            }
        }
        if (ok && (fabs(trc - M * trU) > 1e-8 * sct[k] * D || fabs(frc - M * frU) > 1e-8 * sct[k] * sct[k] * D)) ok = 0;
    }
    if (ok) {
        /* <S2, S3> on the component against M <U'S2U, U'S3U> */
        double ic = 0, iu = 0;
        for (int a = 0; a < nm; a++) for (int i = cs[mem[a]]; i < cs[mem[a] + 1]; i++) for (int b = 0; b < nm; b++) for (int j = cs[mem[b]]; j < cs[mem[b] + 1]; j++) ic += T2[i + (size_t)j * n] * T3[i + (size_t)j * n];
        double *z2 = ax(sizeof(double) * (D + 1)), *z3 = ax(sizeof(double) * (D + 1));
        for (int a = 0; a < nm; a++) { const int sa = cs[mem[a] + 1] - cs[mem[a]];
            for (int p = 0; p < rj[a]; p++) { const double *u = U + uo[a] + (size_t)p * sa;
                for (int b = 0; b < nm; b++) { const int sb = cs[mem[b] + 1] - cs[mem[b]];
                    for (int i = 0; i < sb; i++) { double v2 = 0, v3 = 0; for (int j = 0; j < sa; j++) { const size_t o = (cs[mem[b]] + i) + (size_t)(cs[mem[a]] + j) * n; v2 += T2[o] * u[j]; v3 += T3[o] * u[j]; } z2[i] = v2; z3[i] = v3; }
                    for (int q = 0; q < rj[b]; q++) { const double *w = U + uo[b] + (size_t)q * sb; double d2 = 0, d3 = 0; for (int i = 0; i < sb; i++) { d2 += w[i] * z2[i]; d3 += w[i] * z3[i]; } iu += d2 * d3; } } } }
        free(z2); free(z3);
        if (fabs(ic - M * iu) > 1e-8 * sc2 * sc3 * D) ok = 0;
    }
    free(qa); free(qc); free(y);
    if (!ok) { free(U); return 0; }
    *Uout = U; *Mout = M;
    return r;
}

/* the decomposition of one block; returns the number of components (0: none found) */
static int al_block(const Block *B, int kblk, int verbose, ACmp **out, int *nmult) {
    const int n = B->n, nd = B->ncon + 1;
    *out = NULL; *nmult = 0;
    double *nrm = ax(sizeof(double) * nd);
    for (int t = -1; t < B->ncon; t++) nrm[t + 1] = sp_fro(t < 0 ? &B->C : &B->A[t]);
    al_rng = 0x2545f4914f6cdd1dull ^ ((uint64_t)(kblk + 1) * 0x9e3779b97f4a7c15ull);
    {
        int *lab = ax(sizeof(int) * n), K = 0;
        const int f = al_fast(B, nrm, lab, &K);
        if (f == 1) { free(lab); free(nrm); return -1; }
        if (f == 2) {
            /* a direct sum over the graph components, found combinatorially: Q is a column
             * selection (the reduced data stay sparse) */
            ACmp *C = calloc(K, sizeof(ACmp));
            int *sz = calloc(K, sizeof(int)), *fill = calloc(K, sizeof(int));
            for (int i = 0; i < n; i++) sz[lab[i]]++;
            for (int c = 0; c < K; c++) { C[c].d = sz[c]; C[c].mult = 1; C[c].Q = calloc((size_t)n * sz[c], sizeof(double)); }
            for (int i = 0; i < n; i++) { const int c = lab[i]; C[c].Q[i + (size_t)(fill[c]++) * n] = 1.0; }
            free(sz); free(fill); free(lab); free(nrm);
            *out = C;
            return K;
        }
        free(lab);
    }
    const size_t nn = (size_t)n * n;
    double *V = ax(sizeof(double) * nn), *T2 = ax(sizeof(double) * nn), *T3 = ax(sizeof(double) * nn), *W = ax(sizeof(double) * nn), *w = ax(sizeof(double) * n);
    int *cs = ax(sizeof(int) * (n + 1)), nc = 0, amb = 0;
    const double te0 = wtime();
    for (int tr = 0; tr < 3; tr++) {
        al_combo(B, nrm, V);
        int lw = -1, liw = -1, info = 0; double wq; int iq;
        BL(dsyevd_)("V", "U", &n, V, &n, w, &wq, &lw, &iq, &liw, &info);
        lw = (int)wq + 1; liw = iq + 1;
        double *wk = ax(sizeof(double) * lw); int *iw = ax(sizeof(int) * liw);
        BL(dsyevd_)("V", "U", &n, V, &n, w, wk, &lw, iw, &liw, &info);
        free(wk); free(iw);
        if (info) { nc = 0; break; }
        const double sc = fmax(fabs(w[0]), fabs(w[n - 1]));
        if (sc <= 0) { nc = 0; break; }
        nc = 0; amb = 0; cs[nc++] = 0;
        for (int i = 1; i < n; i++) {
            const double g = w[i] - w[i - 1];
            if (g > 1e-6 * sc) cs[nc++] = i;          /* a new cluster */
            else if (g > 1e-9 * sc) amb++;            /* close but not equal: merged (exact, coarser) */
        }
        cs[nc] = n;
        if (getenv("BRISK_ALGDBG")) printf("   [algebra: block %d n %d try %d: %d clusters, %d ambiguous gaps, %.2fs]\n", kblk + 1, n, tr, nc, amb, wtime() - te0);
        if (!amb) break;                              /* else another S1 */
    }
    int ncomp = 0;
    ACmp *C = NULL;
    double *GK[AL_K] = { NULL };   /* the closure's generators (the irreducible path), built on demand */
    if (nc >= 2 || (nc == 1 && n >= 2)) {
        al_combo(B, nrm, T2); al_rotate(n, V, T2, W);
        double sc2 = 0, sc3 = 0;
        for (size_t q = 0; q < nn; q++) sc2 = fmax(sc2, fabs(T2[q]));
        /* clusters -> components (coupled by S2, then S3) */
        int *uf = ax(sizeof(int) * nc); for (int i = 0; i < nc; i++) uf[i] = i;
        double *cw = calloc((size_t)nc * nc, sizeof(double));   /* coupling weights (S2) for the spanning tree */
        int maxdim = 0;
        for (int i = 0; i < nc; i++) { if (cs[i + 1] - cs[i] > maxdim) maxdim = cs[i + 1] - cs[i];
            for (int j = i + 1; j < nc; j++) {
                const double c2 = al_blkfro(n, T2, cs[i], cs[i + 1], cs[j], cs[j + 1]);
                cw[i + (size_t)j * nc] = cw[j + (size_t)i * nc] = c2 / sc2;
                if (c2 > 1e-10 * sc2) { const int a = al_find(uf, i), b = al_find(uf, j); if (a != b) uf[a] = b; }
            } }
        if (getenv("BRISK_ALGDBG")) printf("   [algebra: S2 couplings done %.2fs]\n", wtime() - te0);
        int one = 1; for (int i = 1; i < nc && one; i++) if (al_find(uf, i) != al_find(uf, 0)) one = 0;
        if (one && maxdim == 1) {
            /* simple spectrum and S2 couples everything: A = M_n (S3 cannot split it further) */
            free(uf); free(cw);
            free(V); free(T2); free(T3); free(W); free(w); free(cs); free(nrm);
            return 0;
        }
        al_combo(B, nrm, T3); al_rotate(n, V, T3, W);
        for (size_t q = 0; q < nn; q++) sc3 = fmax(sc3, fabs(T3[q]));
        for (int i = 0; i < nc; i++) for (int j = i + 1; j < nc; j++) {
            if (al_find(uf, i) == al_find(uf, j)) continue;
            if (al_blkfro(n, T3, cs[i], cs[i + 1], cs[j], cs[j + 1]) > 1e-10 * sc3) { const int a = al_find(uf, i), b = al_find(uf, j); if (a != b) uf[a] = b; }
        }
        int *cid = ax(sizeof(int) * nc), *rid = ax(sizeof(int) * nc);
        for (int i = 0; i < nc; i++) rid[i] = -1;
        for (int i = 0; i < nc; i++) { const int r = al_find(uf, i); if (rid[r] < 0) rid[r] = ncomp++; cid[i] = rid[r]; }
        C = calloc(ncomp, sizeof(ACmp));
        int *mem = ax(sizeof(int) * nc);
        for (int c = 0; c < ncomp; c++) {
            int nm = 0, m = -1, same = 1, dim = 0;
            for (int i = 0; i < nc; i++) if (cid[i] == c) { mem[nm++] = i; const int s = cs[i + 1] - cs[i]; dim += s; if (m < 0) m = s; else if (s != m) same = 0; }
            int okm = same && m >= 2;
            double *O = NULL;
            if (okm) {
                /* align the cluster bases along a maximal spanning tree of the S2 couplings */
                O = calloc((size_t)nm * m * m, sizeof(double));
                double *G = ax(sizeof(double) * m * m), *wk = ax(sizeof(double) * m * m);
                char *in = calloc(nm, 1); double *best = ax(sizeof(double) * nm); int *from = ax(sizeof(int) * nm);
                for (int a = 0; a < m; a++) O[a + a * m] = 1.0;
                in[0] = 1;
                for (int a = 0; a < nm; a++) { best[a] = cw[mem[0] + (size_t)mem[a] * nc]; from[a] = 0; }
                for (int step = 1; step < nm && okm; step++) {
                    int jb = -1; for (int a = 0; a < nm; a++) if (!in[a] && (jb < 0 || best[a] > best[jb])) jb = a;
                    const int ia = from[jb];
                    al_cpl(n, m, T2, cs[mem[ia]], cs[mem[jb]], O + (size_t)ia * m * m, NULL, G, wk);
                    double f = 0; for (int q = 0; q < m * m; q++) f += G[q] * G[q];
                    const double s = sqrt(f / m);
                    if (!(s > 1e-8)) { okm = 0; break; }
                    /* G' G = s^2 I ? */
                    for (int b = 0; b < m && okm; b++) for (int a = 0; a < m && okm; a++) {
                        double v = 0; for (int q = 0; q < m; q++) v += G[q + a * m] * G[q + b * m];
                        if (fabs(v / (s * s) - (a == b)) > 1e-7) okm = 0;
                    }
                    double *Oj = O + (size_t)jb * m * m;
                    for (int b = 0; b < m; b++) for (int a = 0; a < m; a++) Oj[a + b * m] = G[b + a * m] / s;   /* O_j = G' / s */
                    in[jb] = 1;
                    for (int a = 0; a < nm; a++) if (!in[a] && cw[mem[jb] + (size_t)mem[a] * nc] > best[a]) { best[a] = cw[mem[jb] + (size_t)mem[a] * nc]; from[a] = jb; }
                }
                /* verify: every coupling of S2 and S3 is a multiple of I in the aligned bases */
                for (int a = 0; a < nm && okm; a++) for (int b = a; b < nm && okm; b++) {
                    al_cpl(n, m, T2, cs[mem[a]], cs[mem[b]], O + (size_t)a * m * m, O + (size_t)b * m * m, G, wk);
                    if (!al_scalar(m, G, sc2, 1e-9)) okm = 0;
                    al_cpl(n, m, T3, cs[mem[a]], cs[mem[b]], O + (size_t)a * m * m, O + (size_t)b * m * m, G, wk);
                    if (okm && !al_scalar(m, G, sc3, 1e-9)) okm = 0;
                }
                free(G); free(wk); free(in); free(best); free(from);
                if (verbose > 1 && !okm) printf("   algebra symmetry: block %d component %d (%d clusters of %d): multiplicity not verified, kept as one block of %d\n", kblk + 1, c, nm, m, dim);
            }
            if (okm) {
                const int d = nm, M = m;
                C[c].d = d; C[c].mult = M; C[c].Q = ax(sizeof(double) * (size_t)n * d * M);
                double *Wt = ax(sizeof(double) * (size_t)n * M); const double one = 1.0, zero = 0.0;
                for (int a = 0; a < nm; a++) {
                    BL(dgemm_)("N", "N", &n, &M, &M, &one, V + (size_t)cs[mem[a]] * n, &n, O + (size_t)a * M * M, &M, &zero, Wt, &n);
                    for (int r = 0; r < M; r++) memcpy(C[c].Q + (size_t)(r * d + a) * n, Wt + (size_t)r * n, sizeof(double) * n);
                }
                free(Wt);
                (*nmult)++;
            } else {
                /* complex or quaternion type (or an unverified real one): one irreducible copy,
                 * X = M U Y U' on the component (exact; not the symmetric representative) */
                double *Uc = NULL; int *uo = ax(sizeof(int) * nm), *rj = ax(sizeof(int) * nm), M = 0;
                int r = 0;
                if (dim >= 4 && n <= 2000) {
                    if (!GK[0]) for (int k = 0; k < AL_K; k++) { GK[k] = ax(sizeof(double) * nn); al_combo(B, nrm, GK[k]); }
                    r = al_irred(n, V, GK, AL_K, T2, T3, sc2, sc3, cs, mem, nm, &Uc, uo, rj, &M);
                }
                if (r > 0) {
                    C[c].d = r; C[c].mult = 1; C[c].rep = M; C[c].Q = calloc((size_t)n * r, sizeof(double));
                    const double sq = sqrt((double)M); int col = 0;
                    for (int a = 0; a < nm; a++) { const int sa = cs[mem[a] + 1] - cs[mem[a]];
                        for (int p = 0; p < rj[a]; p++, col++) { const double *u = Uc + uo[a] + (size_t)p * sa; double *q = C[c].Q + (size_t)col * n;
                            for (int j = 0; j < sa; j++) { const double f = sq * u[j]; const double *v = V + (size_t)(cs[mem[a]] + j) * n; for (int i = 0; i < n; i++) q[i] += f * v[i]; } } }
                    free(Uc); (*nmult)++;
                    if (verbose > 1) printf("   algebra symmetry: block %d component %d: one irreducible copy of %d with multiplicity %d (complex or quaternion type)\n", kblk + 1, c, r, M);
                    free(uo); free(rj); free(O);
                    continue;
                }
                free(uo); free(rj);
                C[c].d = dim; C[c].mult = 1; C[c].Q = ax(sizeof(double) * (size_t)n * dim);
                int p = 0; for (int a = 0; a < nm; a++) for (int i = cs[mem[a]]; i < cs[mem[a] + 1]; i++) memcpy(C[c].Q + (size_t)(p++) * n, V + (size_t)i * n, sizeof(double) * n);
            }
            free(O);
        }
        free(mem); free(uf); free(cw); free(cid); free(rid);
        if (ncomp == 1 && C[0].mult == 1) { free(C[0].Q); free(C); C = NULL; ncomp = 0; }
    }
    for (int k = 0; k < AL_K; k++) free(GK[k]);
    free(V); free(T2); free(T3); free(W); free(w); free(cs); free(nrm);
    *out = C;
    return ncomp;
}

PSAlg *alg_reduce(Problem *P, int mode, int maxn, double symmin, int verbose) {
    if (!mode) return NULL;
    const double t0 = wtime();
    const int nb = P->nblk, m = P->m;
    ACmp **cmp = calloc(nb, sizeof(ACmp *)); int *ncmp = calloc(nb, sizeof(int));
    int any = 0, nfast = 0, ntried = 0;
    for (int k = 0; k < nb; k++) {
        const Block *B = &P->blk[k];
        if (B->type != BLK_SDP || B->n < 2) continue;
        if (mode < 0 && B->n > maxn) continue;
        if (B->ncon == 0 && B->C.nnz == 0) continue;
        if (brisk_stop_flag) break;        /* 4.42: Ctrl-C / brisk_interrupt(): the blocks not yet checked stay as they are */
        ntried++;
        int nmu = 0;
        const int nc = al_block(B, k, verbose, &cmp[k], &nmu);
        if (nc < 0) { nfast++; continue; }
        if (nc == 0) continue;
        double c0 = (double)B->n * B->n * B->n, c1 = 0;
        for (int c = 0; c < nc; c++) c1 += (double)cmp[k][c].d * cmp[k][c].d * cmp[k][c].d;
        if (c0 / fmax(c1, 1.0) < (mode > 0 ? 1.0 + 1e-9 : symmin)) {
            if (verbose > 0) printf("   algebra symmetry: block %d (n = %d): %d component(s), gain %.2f below %g: not applied\n", k + 1, B->n, nc, c0 / fmax(c1, 1.0), symmin);
            for (int c = 0; c < nc; c++) free(cmp[k][c].Q);
            free(cmp[k]); cmp[k] = NULL; continue;
        }
        ncmp[k] = nc; any = 1;
    }
    if (!any) {
        if (verbose > 0 && ntried) printf("   algebra symmetry: none (%d block(s) checked, %d by the fast test, %.2fs)\n", ntried, nfast, wtime() - t0);
        free(cmp); free(ncmp); return NULL;
    }
    if (getenv("BRISK_ALGDBG")) printf("   [algebra: analysis %.3fs]\n", wtime() - t0);
    /* the reduced data: m_c U' A U for the first copy U of each component (rows of A only) */
    int ng = 0; for (int k = 0; k < nb; k++) ng += ncmp[k];
    int *gk = ax(sizeof(int) * (ng + 1)), *g0 = ax(sizeof(int) * (nb + 1));
    { int g = 0; for (int k = 0; k < nb; k++) { g0[k] = g; for (int c = 0; c < ncmp[k]; c++) gk[g++] = k; } g0[nb] = g; }
    size_t cap = 1024, nt = 0;
    int *tc = ax(sizeof(int) * cap), *tg = ax(sizeof(int) * cap), *ti = ax(sizeof(int) * cap), *tj = ax(sizeof(int) * cap); double *tv = ax(sizeof(double) * cap);
#define AL_PUSH(c_, g_, i_, j_, v_) do { if (nt == cap) { cap *= 2; tc = realloc(tc, sizeof(int) * cap); tg = realloc(tg, sizeof(int) * cap); ti = realloc(ti, sizeof(int) * cap); tj = realloc(tj, sizeof(int) * cap); tv = realloc(tv, sizeof(double) * cap); if (!tc || !tg || !ti || !tj || !tv) { fprintf(stderr, "brisk: out of memory (algebra symmetry)\n"); exit(1); } } \
        tc[nt] = (c_); tg[nt] = (g_); ti[nt] = (i_); tj[nt] = (j_); tv[nt] = (v_); nt++; } while (0)
    char *nz = calloc(ng + 1, 1);
    for (int k = 0; k < nb; k++) {
        const Block *B = &P->blk[k];
        if (!ncmp[k]) {
            /* kept as it is: tg = -(k + 1) */
            const int lp = B->type == BLK_LP;
            for (int t = -1; t < B->ncon; t++) { const SpSym *A = t < 0 ? &B->C : &B->A[t]; const int c = t < 0 ? -1 : B->con[t];
                for (int q = 0; q < A->nnz; q++) AL_PUSH(c, -(k + 1), A->row[q], lp ? A->row[q] : A->col[q], A->val[q]); }
            continue;
        }
        const int n = B->n; int D = 0, dmax = 0;
        for (int c = 0; c < ncmp[k]; c++) { D += cmp[k][c].d; if (cmp[k][c].d > dmax) dmax = cmp[k][c].d; }
        int *loc = ax(sizeof(int) * n), *rows = ax(sizeof(int) * n);
        for (int i = 0; i < n; i++) loc[i] = -1;
        double *UR = ax(sizeof(double) * (size_t)n * D), *YR = ax(sizeof(double) * (size_t)n * D), *Bm = ax(sizeof(double) * (size_t)dmax * dmax);
        for (int t = -1; t < B->ncon; t++) {
            const SpSym *A = t < 0 ? &B->C : &B->A[t]; const int con = t < 0 ? -1 : B->con[t];
            if (A->nnz == 0) continue;
            int r = 0; double fro = 0;
            for (int q = 0; q < A->nnz; q++) { const int a = A->row[q], b = A->col[q]; if (loc[a] < 0) { loc[a] = r; rows[r++] = a; } if (loc[b] < 0) { loc[b] = r; rows[r++] = b; } fro += (a == b ? 1.0 : 2.0) * A->val[q] * A->val[q]; }
            fro = sqrt(fro);
            /* UR (r x D): rows of the first copies; YR = A_RR UR */
            { int col = 0; for (int c = 0; c < ncmp[k]; c++) for (int i = 0; i < cmp[k][c].d; i++, col++) { const double *u = cmp[k][c].Q + (size_t)i * n; for (int a = 0; a < r; a++) UR[a + (size_t)col * r] = u[rows[a]]; } }
            memset(YR, 0, sizeof(double) * (size_t)r * D);
            for (int q = 0; q < A->nnz; q++) {
                const int a = loc[A->row[q]], b = loc[A->col[q]]; const double v = A->val[q];
                for (int col = 0; col < D; col++) { YR[a + (size_t)col * r] += v * UR[b + (size_t)col * r]; if (a != b) YR[b + (size_t)col * r] += v * UR[a + (size_t)col * r]; }
            }
            int col0 = 0;
            for (int c = 0; c < ncmp[k]; c++) {
                const int d = cmp[k][c].d; const double one = 1.0, zero = 0.0;
                BL(dgemm_)("T", "N", &d, &d, &r, &one, UR + (size_t)col0 * r, &r, YR + (size_t)col0 * r, &r, &zero, Bm, &d);
                const int g = g0[k] + c; const double mu = cmp[k][c].mult;
                for (int j = 0; j < d; j++) for (int i = 0; i <= j; i++) {
                    const double v = 0.5 * (Bm[i + j * d] + Bm[j + i * d]);
                    if (fabs(v) > 1e-13 * fro) { AL_PUSH(con, g, i, j, mu * v); nz[g] = 1; }
                }
                col0 += d;
            }
            for (int a = 0; a < r; a++) loc[rows[a]] = -1;
        }
        free(loc); free(rows); free(UR); free(YR); free(Bm);
    }
    /* the reduced blocks: kept blocks and components of size >= 2 in order, then one LP block
     * with the components of size 1; components without data are dropped (X = 0 there) */
    PSAlg *S = calloc(1, sizeof(PSAlg));
    S->m = m; S->nblk = nb; S->ncomp = ng;
    S->bs = ax(sizeof(int) * nb); S->bmap = ax(sizeof(int) * nb);
    S->ck = ax(sizeof(int) * (ng + 1)); S->cd = ax(sizeof(int) * (ng + 1)); S->cm = ax(sizeof(int) * (ng + 1)); S->crb = ax(sizeof(int) * (ng + 1)); S->cpos = ax(sizeof(int) * (ng + 1)); S->cQ = calloc(ng + 1, sizeof(double *));
    int rb = 0, nlp = 0, ndrop = 0;
    for (int k = 0; k < nb; k++) {
        S->bs[k] = P->blk[k].type == BLK_LP ? -P->blk[k].n : P->blk[k].n;
        S->bmap[k] = -1;
        if (!ncmp[k]) { S->bmap[k] = rb++; continue; }
        for (int c = 0; c < ncmp[k]; c++) {
            const int g = g0[k] + c;
            S->ck[g] = k; S->cd[g] = cmp[k][c].d; S->cm[g] = cmp[k][c].mult; S->cQ[g] = cmp[k][c].Q; S->cpos[g] = 0;
            if (!nz[g]) { S->crb[g] = -1; ndrop++; }
            else if (cmp[k][c].d >= 2) S->crb[g] = rb++;
            else { S->crb[g] = -2; S->cpos[g] = nlp++; }
        }
    }
    const int lpb = rb; if (nlp) rb++;
    for (int g = 0; g < ng; g++) if (S->crb[g] == -2) S->crb[g] = lpb;
    S->nbr = rb; S->lpblk = nlp ? lpb : -1;
    int *bsz = ax(sizeof(int) * (rb + 1)), *tb = ax(sizeof(int) * (nt + 1));
    for (int k = 0; k < nb; k++) if (S->bmap[k] >= 0) bsz[S->bmap[k]] = S->bs[k];
    for (int g = 0; g < ng; g++) if (S->crb[g] >= 0 && S->crb[g] != lpb) bsz[S->crb[g]] = S->cd[g];
    if (nlp) bsz[lpb] = -nlp;
    size_t w2 = 0;
    for (size_t q = 0; q < nt; q++) {
        if (tg[q] < 0) { tb[w2] = S->bmap[-tg[q] - 1]; tc[w2] = tc[q]; ti[w2] = ti[q]; tj[w2] = tj[q]; tv[w2] = tv[q]; w2++; continue; }
        const int g = tg[q]; if (S->crb[g] < 0) continue;
        tb[w2] = S->crb[g]; tc[w2] = tc[q];
        if (S->crb[g] == lpb && nlp) { ti[w2] = tj[w2] = S->cpos[g]; } else { ti[w2] = ti[q]; tj[w2] = tj[q]; }
        tv[w2] = tv[q]; w2++;
    }
    if (getenv("BRISK_ALGDBG")) printf("   [algebra: reduced data %.3fs, %zu entries]\n", wtime() - t0, w2);
    Problem Qp; memset(&Qp, 0, sizeof(Qp));
    problem_from_trips(&Qp, m, rb, bsz, P->b, w2, tc, tb, ti, tj, tv);
    if (getenv("BRISK_ALGDBG")) printf("   [algebra: problem built %.3fs]\n", wtime() - t0);
    Qp.tbR = P->tbR; Qp.obj_off = P->obj_off; Qp.morig = m;
    for (int i = 0; i < m; i++) Qp.orig[i] = i;
    if (verbose >= 0) {
        printf("presolve: algebra symmetry:");
        int nshown = 0, ndec = 0;
        for (int k = 0; k < nb; k++) ndec += ncmp[k] > 0;
        for (int k = 0; k < nb; k++) {
            if (!ncmp[k]) continue;
            if (nshown++ == 6 && ndec > 7 && verbose < 2) { printf(" ... (%d blocks split in all);", ndec); break; }
            printf(" block %d: %d ->", k + 1, P->blk[k].n);
            int n1 = 0;
            for (int c = 0; c < ncmp[k]; c++) { const int g = g0[k] + c; if (S->crb[g] < 0) continue; if (S->cd[g] == 1) { n1++; continue; } if (S->cm[g] > 1) printf(" %d(x%d)", S->cd[g], S->cm[g]); else if (cmp[k][c].rep > 1) printf(" %d(x%d, c/q)", S->cd[g], cmp[k][c].rep); else printf(" %d", S->cd[g]); }
            if (n1) printf(" %dx1", n1);
            printf(";");
        }
        if (ndrop) printf(" %d empty component(s) dropped;", ndrop);
        printf(" %.2fs\n", wtime() - t0);
    }
    problem_free(P); *P = Qp;
    for (int k = 0; k < nb; k++) free(cmp[k]);
    free(cmp); free(ncmp); free(gk); free(g0); free(tc); free(tg); free(ti); free(tj); free(tv); free(tb); free(bsz); free(nz);
#undef AL_PUSH
    return S;
}

/* back to the blocks before the reduction: X = sum_c Q_c (I_m (x) X_c) Q_c', y unchanged */
void alg_unmap(const PSAlg *S, double **Xred, const double *yred, double **Xo, double *yo) {
    memcpy(yo, yred, sizeof(double) * S->m);
    if (!Xred || !Xo) return;
    for (int k = 0; k < S->nblk; k++) {
        const int n = abs(S->bs[k]);
        const size_t sz = S->bs[k] < 0 ? (size_t)n : (size_t)n * n;
        if (S->bmap[k] >= 0) { memcpy(Xo[k], Xred[S->bmap[k]], sizeof(double) * sz); continue; }
        memset(Xo[k], 0, sizeof(double) * sz);
    }
    for (int g = 0; g < S->ncomp; g++) {
        if (S->crb[g] < 0) continue;
        const int k = S->ck[g], n = S->bs[k], d = S->cd[g], M = S->cm[g], dm = d * M;
        const double *Xc; double x1;
        if (S->crb[g] == S->lpblk && d == 1) { x1 = Xred[S->lpblk][S->cpos[g]]; Xc = &x1; } else Xc = Xred[S->crb[g]];
        double *Y = ax(sizeof(double) * (size_t)n * dm); const double one = 1.0, zero = 0.0;
        for (int r = 0; r < M; r++) BL(dgemm_)("N", "N", &n, &d, &d, &one, S->cQ[g] + (size_t)r * d * n, &n, Xc, &d, &zero, Y + (size_t)r * d * n, &n);
        BL(dgemm_)("N", "T", &n, &n, &dm, &one, Y, &n, S->cQ[g], &n, &one, Xo[k], &n);
        free(Y);
    }
}

void alg_free(PSAlg *S) {
    if (!S) return;
    for (int g = 0; g < S->ncomp; g++) free(S->cQ[g]);
    free(S->cQ); free(S->bs); free(S->bmap); free(S->ck); free(S->cd); free(S->cm); free(S->crb); free(S->cpos); free(S);
}
